### ISSUE TITLE
Zuordnung Gemarkung - Gemeinde

### ISSUE THREAD

**Issue by fb71** [fb71/polymap4-alkis#19]
http://www.polymap.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=632

bei ALKIS (polmap4) erfolgt immer noch eine fehlerhafte Zuordnung von
Gemarkung und Gemeinde. Ich nehme an, das die Tabelle "ax_gemeinde"
Spalte "schluesselgesamt" für die Zuordnung der Gemeinde zur Gemarkung
verwendet wurde. In dieser Tabelle sind zumindest die Gemeinden
enthalten, die zwar nicht im Landkreis Wittenberg liegen aber
Gemarkungen im Landkreis zugeordnet wurden. In ax_gemeinde sind
(höchstwahrscheinlich) alle Gemeinden Sachsen-Anhalts gelistet. Die
ebenfalls vorhandene Tabelle "gem-shl" wäre möglichweise (ich kenne
nicht mögliche andere Abhängigkeiten) die geeignetere Tabelle zur
Verknüpfung mit den Gemarkungen. Diese ist eine Selektion aus der
"ax_gemeinde", für den Landkreis Wittenberg. 

Unabhängig davon: die Schlüsselnummern zur Zuordnung von Gemeinde und
Gemarkung sind in beiden Tabellen "ax_gemeinde.schluesselgesamt " und
"gem_shl.gemshl" identisch. Warum die unten aufgeführten fehlerhaften
Zuordnungen auftreten erschließt sich mir leider nicht. Ich bitte das
umgehend zu korrigieren.

Gemeinde SchlNr. --- Fehlerhafte Gemeinde SchlNr.
Coswig 15091060 - Beendorf 15083060
Lutherstadt Wittenberg 15091375- Osterfeld, Stadt 15084375
Bad Schmiedeberg 15091060 - Bad Dürrenberg, Stadt 15088020
Kemberg 15091160- Hedersleben 15085160
Jessen 15091145- Möser 15086145
Annaburg 15091010- Ahlsdorf 15087010
Gräfenhainichen 15091110- Falkenstein/Harz, Stadt 15085110
　
Zahna-Elster, Stadt ------ korrekt
Oranienbaum-Wörlitz -----korrekt
Beste Grüße
Olaf Roehling

**Comment by fb71** [comment]
@roehlingol: in "ax_flurstueck" gibt es die Spalte "gemeinde". Diese Spalte gibt es ebenfalls in "ax_gemeinde". Darüber wird die Beziehung von Flurstück zu Gemeinde hergestellt. Bei Gemarkung heißt die Spalte "gemarkungsnummer". Die Beziehung von Flurstück zu Gemarkung wird unabhängig von der Germeinde über diese Spalte hergestellt.

Der ALKIS-OK sagt dazu: _'Gemarkungsnummer' enthält die von der Katasterbehörde zur eindeutigen Bezeichnung der Gemarkung vergebene Nummer innerhalb eines Bundeslandes._

Leider habe ich auch noch nicht ganz verstanden was genau falsch zugeordnet wird. Könnten Sie mir bitte ein konkretes Flustück sagen, was daran falsch ist und wie es richtig sein müsste? Dann kann ich genau sehen welche Schlüssel wo stehen. Vielen Dank.

**Comment by fb71** [comment]
@roehlingol: in "gem_shl" stehen nur 13 Zeilen. Sind das eventuell die, die auch falsch angezeigt werden? Können Sie das nachvollziehen?

**Comment by fb71** [comment]
@roehlingol: aber egal welcher "schluesselgesamt" nun richtig ist, ich sehe im Moment nicht, wo ich diesen am Flurstück finde. Wie also die Referenz hergestellt wird. Können Sie mir das sagen?

**Comment by roehlingol** [comment]
Beispiel Gemarkung Annaburg, hier wird als Gemeinde Ahlsdorf angezeigt. 
Die in der Tabelle **ax_gemeinde** vorhandene Spalte **gemeinde** enthält nur die letzten 3 Ziffern der Gemeindeschlüsselnummer.
Die ist im Beispiel die Gleiche von **Annaburg, Stadt** - **Ahlsdorf**  und sogar noch **Arneburg, Stadt** - 010.
Entscheidend ist wohl die dazugehörende Spalte **kreis**. Landkreis Wittenberg hat die 91.
Die Kombination aus kreis+gemeinde (Nummer), die sowohl in der Tabelle **ax_gemeinde** als auch in **ax_flurstueck** existieren sollte die korrekte Gemeinde zum Flurstück zuordnen.
(Die Gemeindeschlüsselnummer setzt sich insgesamt aus 
**land+regierungsbezirk+kreis+gemeinde**
zusammen).
Ich hoffe das trägt ein bisschen zur Klarheit bei.

**Comment by fb71** [comment]
Vielen Dank nochmal für die sehr guten Erklärungen, die haben wirklich sehr geholfen. Leider hat es dann nochmal eine Weile gedauert, bis wir das in Software umsetzen konnten, nun ist es aber geschafft. Eine neue Version ist installiert und aktualisiert gerade den Index. Sie können trotzdem parallel testen ob die Gemeinden nun korrekt angezeigt werden.
